# docker-compose.yml

version: '3.8'

services:
  webf:
    build: .
      #command: bash -c "sleep 10; uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    command: bash -c "sleep 10; python3 app.py"
    volumes:
      - .:/app
    ports:
        - 8000:8000    
        - 8050:8050  
    expose:  # new
      - 8000
      - 8050
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    container_name: "neo4j"
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/var/lib/neo4j/import
    expose:
      - 7687
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/password"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      - NEO4JLABS_PLUGINS=["apoc"]
